
import 'package:jxim_client/utils/color.dart';
import 'package:flutter/material.dart';

class TextFieldLight extends TextField {
  const TextFieldLight({
    super.key,
    super.focusNode,
    super.controller,
    super.textDirection,
    super.textAlignVertical,
    super.textCapitalization,
    super.keyboardType,
    super.textInputAction,
    super.textAlign,
    super.style,
    super.strutStyle,
    super.cursorColor,
    super.keyboardAppearance = txtBrightness,
    super.readOnly,
    super.showCursor,
    super.toolbarOptions,
    super.autofocus,
    super.obscuringCharacter,
    super.obscureText,
    super.autocorrect,
    super.smartDashesType,
    super.smartQuotesType,
    super.enableSuggestions,
    int super.maxLines,
    super.minLines,
    super.expands,
    super.maxLength,
    super.decoration = null,
    super.onChanged,
    super.onSubmitted,
    bool maxLengthEnforced = true,
    super.maxLengthEnforcement,
    super.onEditingComplete,
    super.onAppPrivateCommand,
    super.inputFormatters,
    super.enabled,
    super.cursorWidth,
    super.cursorHeight,
    super.cursorRadius,
    super.selectionHeightStyle,
    super.selectionWidthStyle,
    super.scrollPadding,
    super.dragStartBehavior,
    bool super.enableInteractiveSelection = true,
    super.selectionControls,
    super.onTap,
    super.mouseCursor,
    super.buildCounter,
    super.scrollController,
    super.scrollPhysics,
    super.autofillHints = null,
    super.restorationId,
    super.enableIMEPersonalizedLearning,
  });
}
