final errorCodeToKick = [
  ErrorCodeConstant.STATUS_JWT_INVALID,
  ErrorCodeConstant.STATUS_SESSION_INVALID,
  ErrorCodeConstant.STATUS_ERR_PARSING_KEY,
  ErrorCodeConstant.STATUS_ERR_SIGNING_METHOD,
  ErrorCodeConstant.STATUS_REFRESH_TOKEN_FAILED,
  ErrorCodeConstant.STATUS_USER_LOGGED_IN_ANOTHER_DEVICE,
];

class ErrorCodeConstant {
  ///通用错误码
  static const STATUS_DB_ERROR = 10001;
  static const STATUS_UPDATE_VERSION = 10002;
  static const STATUS_PARAMS_EMPTY = 10003;
  static const STATUS_PERMISSION_DENY = 10004;

  /// 群组错误
  static const STATUS_NOT_IN_CHAT = 20002;

  /// 被拉黑错误
  static const STATUS_USER_HE_IN_BLACKLIST = 20307;
  static const STATUS_USER_ME_IN_BLACKLIST = 20308;

  ///服务共用错误码
  static const STATUS_AUTHENTICATION_FAILED = 30001;
  static const STATUS_JWT_EXPIRED = 30002;
  static const STATUS_JWT_INVALID = 30003;
  static const STATUS_GENERATE_JWT_FAILED = 30004;
  static const STATUS_USER_LOGGED_IN_ANOTHER_DEVICE = 30006;
  static const STATUS_ERR_SIGNING_METHOD = 30008;
  static const STATUS_ERR_PARSING_KEY = 30009;

  ///用户
  static const STATUS_USER_NOT_EXIST = 30101;
  static const STATUS_USER_ALREADY_EXIST = 30102;
  static const STATUS_VCODE_ERROR = 30103;
  static const STATUS_SEND_VCODE_ERROR = 30104;
  static const STATUS_REGION_CODE_ERROR = 30105;
  static const STATUS_INVALID_CONTACT = 30106;
  static const STATUS_REGISTER_FAILED = 30107;
  static const STATUS_LOGIN_FAILED = 30108;
  static const STATUS_UPDATE_USER_DETAIL_FAILED = 30109;
  static const STATUS_MFA_ACTIVATE_FAILED = 30110;
  static const STATUS_MFA_DEACTIVATE_FAILED = 30111;
  static const STATUS_DELETE_USER_FAILED = 30112;
  static const STATUS_GET_USER_PROFILE_FAILED = 30113;
  static const STATUS_UPDATE_USERNAME_QUOTA_EXCEEDED = 30114;
  static const STATUS_OTP_REACH_LIMIT = 30116;
  static const STATUS_PHONE_ALREADY_EXIST = 30117;
  static const STATUS_EMAIL_ALREADY_EXIST = 30139;
  static const STATUS_SESSION_INVALID = 30124;
  static const STATUS_REFRESH_TOKEN_FAILED = 30125;
  static const STATUS_NOT_LOGGED_IN_DESKTOP = 30126;
  static const STATUS_NO_LOGIN_REQUEST = 30127;
  static const STATUS_LOGIN_QR_EXPIRED_DESKTOP = 30128;
  static const STATUS_BLOCK_NUMBER = 30142;
  static const STATUS_BLOCK_EMAIL = 30143;
  static const STATUS_BLOCK_USERNAME = 30144;
  static const STATUS_OTP_BE_REACH_LIMIT = 30146;
  static const STATUS_INVITE_CODE_ERROR = 30157;
  static const STATUS_NEED_INVITE_CODE = 30159;

  ///好友
  static const STATUS_SYSTEM_ERROR = 30200;
  static const STATUS_NOT_FRIEND = 30201;
  static const STATUS_NOT_IN_BLACKLIST = 30202;
  static const STATUS_IN_BLACKLIST = 30203;
  static const STATUS_ADD_FRIEND_FAILED = 30204;
  static const STATUS_BLACKLIST_FAILED = 30205;
  static const STATUS_REMOVE_BLACKLIST_FAILED = 30206;
  static const STATUS_SEND_FRIEND_REQUEST_FAILED = 30207;
  static const STATUS_IN_FRIEND = 30208;
  static const STATUS_FRIEND_QUOTA_EXCEED = 30209;
  static const STATUS_TARGET_USER_FRIEND_QUOTA_EXCEED = 30210;
  static const STATUS_REMOVE_CONTACT_FAILED = 30211;
  static const STATUS_REJECT_FRIEND_REQUEST_FAILED = 30212;
  static const STATUS_EDIT_FRIEND_INFO_FAILED = 30213;
  static const STATUS_FAILED_ACCEPT_MULTIPLE = 30215;

  ///设置
  static const STATUS_QUERY_SETTING_FAILED = 30301;

  ///钱包
  static const STATUS_GET_WALLET_SETTING_FAILED = 30401;
  static const STATUS_UPDATE_WALLET_SETTING_FAILED = 30402;
  static const STATUS_INVALID_WALLET_PASSCODE = 30403;
  static const STATUS_SETUP_WALLET_PASSCODE_FAILED = 30404;
  static const STATUS_RESET_WALLET_PASSCODE_FAILED = 30405;
  static const STATUS_TRANSFER_IN_CHAT_FAILED = 30406;
  static const STATUS_SEND_RED_PACKET_FAILED = 30407;
  static const STATUS_RECEIVE_RED_PACKET_FAILED = 30408;
  static const STATUS_MAX_TRY_PASSWORD_WRONG = 30409;

  static const STATUS_INVALID_PARAM = 150001;
  static const STATUS_INVALID_CHANNEL_TYPE = 150002;
  static const STATUS_ID_NOT_EXISTS = 150003;
  static const STATUS_PWD_INCORRECT = 150004;
  static const STATUS_INVALID_ORDER_TYPE = 150005;
  static const STATUS_USER_NOT_EXISTS = 150006;
  static const STATUS_CHAT_NOT_EXISTS = 150007;
  static const STATUS_SEND_RP_NO_PERMISSION = 150008;
  static const STATUS_NEED_OPEN_BLOCKCHAIN_ADDR_WHITE_MODE = 150009;
  static const STATUS_NEW_ADDRESS_IN_24_HOURS_LOCK = 150010;
  static const STATUS_CANNOT_TRANSFER_SELF = 150011;
  static const STATUS_INVALID_V_CODE_TOKEN = 150012;
  static const STATUS_INVALID_BIZ_TYPE = 150013;
  static const STATUS_INVALID_CURRENCY = 150014;
  static const STATUS_PAY_SVC_EXISTS = 150015;
  static const STATUS_PAY_SVC_NOT_EXISTS = 150016;
  static const STATUS_INSUFFICIENT_BALANCE = 150017;
  static const STATUS_RP_AMT_INSUFFICIENT = 150018;
  static const STATUS_EXCEED_MAX_RP_NUM = 150019;
  static const STATUS_EXCEED_MAX_R_P_AMT = 150020;
  static const STATUS_BELOW_MIN_RP_AMT = 150021;
  static const STATUS_CURRENCY_DISABLE = 150022;
  static const STATUS_CODE_REQ_TOO_FREQUENT = 150023;
  static const STATUS_NO_WALLET_PASSCODE = 150024;
  static const STATUS_UNKNOWN = 150099;

  static const INVALID_PARAM = 40001;
  static const INVALID_CURRENCY_TYPE = 40002;
  static const INVALID_NET_TYPE = 40003;
  static const INSUFFICIENT_BALANCE = 40004;
  static const ID_NOT_EXISTS = 40005;
  static const INVALID_CHAIN_ADDR = 40009;
  static const INVALID_USER_ID = 40011;
  static const INVALID_RP_TYPE = 40012;
  static const RECEIVED_RP = 40013;
  static const USER_ID_EXISTS = 40014;
  static const EXPIRED_RP = 40015;
  static const TRANSFER_TO_OWN_ADDR = 40016;
  static const CHAIN_TX_ID_EXISTS = 40017;
  static const BLOCKED_FROM_SPC_RP = 40030;
  static const UNKNOWN = 40099;

  static const EXCEED_MAX_TRANS_AMT = 40301;
  static const BELOW_MIN_TRANS_AMT = 40302;
  static const EXCEED_DAILY_TRANS_AMT = 40303;
  static const EXCEED_DAILY_TRANS_COUNT = 40304;

  static const RP_AMT_INSUFFICIENT = 40401;
  static const EXCEED_MAX_RP_NUM = 40403;

  //加密
  static const ENCRYPTION_KEY_NOT_EXISTS = 31101;
  static const ENCRYPTION_CANNOT_UPDATE_CHAT = 31103;
  static const ENCRYPTION_CANNOT_UPDATE_KEYS = 31105;
}
