name: jxim_client
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.q
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.

# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html

version: 1.0.141+252

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.13.9"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # flutter sdk  3.3.0-0.0.pre  检出命令 `git checkout 3.3.0-0.0.pre`
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  permission_handler: ^10.2.0
  bot_toast: ^4.0.2
  http: ^1.1.0
  protobuf: ^2.0.0
  # aes
  encrypt: 5.0.1
  # 验证码输入框
  pin_code_fields: ^7.4.0
  # SQLite 插件
  sqflite: ^2.0.2+1
  sqflite_common_ffi:
  # 本地存储
  shared_preferences: ^2.0.15
  # 左右滑动删除组件
  flutter_slidable: ^3.1.0
  # 扩展TextField组件
  extended_text_field: ^12.0.1
  # 扫码
  mobile_scanner: 3.4.1
  zxing2: ^0.2.3
  scan: ^1.6.0
  #二维码
  pretty_qr_code: 3.3.0
  # 视频播放器
  video_player: 2.8.3
  # 常用工具类库 包含SharedPreferences Util, Screen Util, Directory Util, Widget Util, Image Util
  flutter_screenutil: ^5.8.4
  # 这个插件允许 Flutter 应用程序发现网络连接并相应地配置自己。它可以区分蜂窝和 WiFi 连接
  connectivity_plus: ^2.3.2
  #文件路径
  path_provider: ^2.0.12

  file_picker: 8.0.0+1

  # 唤醒锁
  # 图片截取
  image_cropper: ^1.5.1
  # 视频压缩
  video_compress: 3.1.2
  # FFMPEG 插件
  ffmpeg_kit_flutter_full_gpl: 6.0.3
  # 震动
  #  vibration: ^1.7.4-nullsafety.0
  #地区码
  country_list_pick:
    path: plugin/country_list_pick
  #屏幕旋转
  auto_orientation: ^2.2.1
  #显示网页
  webview_flutter: ^3.0.4
  # 状态管理 GetX
  get: ^4.6.6
  # 渲染 svg图片
  flutter_svg: ^2.0.9
  # JWT处理
  jwt_decoder: ^2.0.1

  shimmer_animation: ^2.1.0+1

  dismissible_page: ^1.0.2
  #  查看大图
  photo_view: ^0.15.0
  chinese_font_library: 1.1.0
  ########### 私有git库（需要改源码或自定义的包）###########
  # 文件内容显示
  cbb_video_player:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/cbb_video_player.git
      ref: im-ph


  camerawesome:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/camerawesome.git
      ref: im-ph
  #    path: plugin/camerawesome

  # 图片编辑
  image_editor:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/image_editor.git
      ref: im-ph

  screenshot_callback:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/flutter_screenshot.git
      ref: im-ph

  im_diff_plugin:
    # path: plugin/im_diff_plugin
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/im_diff_plugin.git
      ref: im-ph

  sound_mode:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/sound_mode.git
      ref: im-ph
#    path: plugin/sound_mode

  google_maps_flutter:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/google_maps_flutter.git
      ref: im-ph

  ########### 内嵌插件包放这里 ###########
  # 剪切板支持图片
  flutter_pasteboard:
    path: plugin/flutter_pasteboard
  # 录音和播放音频
  flutter_sound_lite:
    path: plugin/flutter_sound_lite-8.5.0
  # 检测手机麦克风是否被其他应用占用
  microphone_in_use:
    path: plugin/microphone_in_use
  # 音频通道调试插件
  audio_session: 0.1.19
  all_sensors: 0.4.2
  audioplayers: ^5.2.0
  # 跳转webview
  url_launcher: ^6.2.1
  # 状态管理
  events_widget:
    path: plugin/events_widget
  # 多图片选择器
  wechat_assets_picker:
    path: plugin/flutter_wechat_assets_picker_new
  # 相机
  wechat_camera_picker:
    path: plugin/flutter_wechat_camera_picker
  # 保存图片到相册
  image_gallery_saver:
    path: plugin/image_gallery_saver

  flutter_fconsole:
    path: plugin/flutter_fconsole
  # 包信息
  package_info_plus: ^4.2.0
  # 设备信息
  device_info_plus: ^9.1.1
  # 音视频通话
  # 盾
  flutter_yun_ceng_kiwi:
    path: plugin/flutter_yun_ceng_kiwi
  flutter_captcha:
    path: plugin/flutter_captcha
  #获取手机本地联系人
  fast_contacts: 3.1.2
  custom_pop_up_menu:
    path: plugin/custom_popup_menu
  #页面辨认使用
  visibility_detector: ^0.3.3
  #选择相册
  image_picker: ^0.8.6+2
  #下载QR使用
  screenshot: 2.1.0
  #表情包
  emojis: ^0.9.9
  open_filex:
    path: plugin/open_filex-master
    #从SIM卡获取资料使用
  flutter_sim_country_code: ^0.1.2
  #辨认手机号
  phone_numbers_parser: ^8.0.0
  #压缩图片
  image_compression_flutter: ^1.0.3
  #转换中文字为拼音
  lpinyin: ^2.0.3
  #辨认电脑版的窗口大小
  desktop_window: ^0.4.0

  # 嵌套滚动控制器
  extended_nested_scroll_view: 6.1.0
  # 长按并放开发送文件
  desktop_drop:
    path: plugin/desktop_drop
  flutter_switch: ^0.3.2

  #堆栈信息采集
  sentry_flutter: 7.18.0

  #桌面端播放视频
  media_kit: ^1.1.7                              # Primary package.
  media_kit_video: ^1.1.8                        # For video rendering.
  media_kit_libs_video: ^1.0.1                   # Native video dependencies.

  #桌面端粘贴图片
  pasteboard: ^0.0.3

  #联系人列表(A-Z分组)
  azlistview:
    path: plugin/az_list_view

  #同步锁
  synchronized: ^3.1.0

  share_plus:
    path: plugin/share_plus

  #网络图片缓存
  extended_image: ^8.1.1
  wakelock_plus: ^1.1.1

  flutter_local_notifications: ^16.3.0

  #偵測link
  flutter_linkify: ^6.0.0

  # 平台推广
  openinstall_flutter_plugin: ^2.4.4

  # 播放声音
  soundpool: ^2.4.1
#  soundpool:
#    path: plugin/soundpool

  social_share: ^2.3.1

  #聊天長列表動畫元件
  flutter_spinkit: ^5.2.0
  calendar_date_picker2: ^0.5.3
  file_selector: ^1.0.1
  sliver_tools: ^0.2.12
  maps_flutter:
    path: plugin/maps_flutter
  geolocator: ^11.0.0
  location: ^5.0.3
  cloud_firestore: ^4.14.0
  firebase_core: ^2.24.2
  geocoding: ^3.0.0
  intl: ^0.18.1
  simple_html_css: ^4.0.0
  in_app_notification: ^1.1.2
  easy_autocomplete: ^1.6.0
  install_plugin: ^2.1.0
  dio: ^5.4.3+1
  lottie_tgs: ^2.7.1
  lottie: ^2.7.0
  dio_smart_retry: ^6.0.0
  video_uploader: ^1.2.1
  collection: ^1.17.2
  translator: ^1.0.0
  pretty_dio_logger: ^1.3.1
  fl_chart: ^0.63.0

  disk_space: ^0.2.1
  scrollable_positioned_list: ^0.2.3
  logger: ^1.4.0
  popover: ^0.2.8+2

  im_common:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/jx-im-plugin/im_common.git
      ref: im-ph
  agora:
    git:
      url: https://4e4d37237693728e2a5f56b31cd5fc06ce3b2237@gitea.cyberbot.work/jx-im-plugin/agora.git
      ref: im-ph
  im:
    git:
      url: https://4e4d37237693728e2a5f56b31cd5fc06ce3b2237@gitea.cyberbot.work/Matrix-Ant-AI/im.git
      ref: im-ph

  im_mini_app_plugin:
    git:
      url: https://4e4d37237693728e2a5f56b31cd5fc06ce3b2237@gitea.cyberbot.work/Matrix-Ant-AI/im_mini_app_manager.git
      ref: im-ph
  im_sticker:
    git:
      url: https://2a5d16efb3659d15f497f5672357bf7a2780692d@gitea.cyberbot.work/Matrix-Ant-AI/im_sticker.git
      ref: im-ph


  #支援markdown文本編輯器
  markdown_editor_plus:
    path: plugin/markdown_editor_plus

  #  flutter_vlc_player:
  #    path: plugin/flutter_vlc_player-7.4.1
  #  flutter_vlc_player_platform_interface:
  #    path: plugin/flutter_vlc_player_platform_interface-2.0.3

  # 开发环境用的，如果你为了导入不报错，这里操作就该死
  # dependency_overrides:
  # http: ^1.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/message/
    - assets/images/
    - assets/images/message_new/
    - assets/images/mypage/
    - assets/images/group/
    - assets/sound/
    - assets/images/voice/
    - assets/images/square_new/
    - assets/images/login_new/
    - assets/images/home/
    - assets/icons/
    - assets/svgs/
    - assets/lottie/
    - assets/svgs/wallet/
    - assets/images/common/
    - assets/images/svg_icon/
    - assets/images/new_resources/
    - assets/images/lottie/
    - assets/images/lottie/react_emoji01/
    - assets/images/red_packet/
    - assets/images/red_packet/message/
    - assets/lang/
    - assets/colors/
  fonts:
    - family: Caveat
      fonts:
        - asset: assets/fonts/Caveat-Han.ttf
    - family: plusjakartasans
      fonts:
        - asset: assets/fonts/plusjakartasans_bold.ttf
        - asset: assets/fonts/plusjakartasans_extrabold.ttf
        - asset: assets/fonts/plusjakartasans_medium.ttf
        - asset: assets/fonts/plusjakartasans_regular.ttf
        - asset: assets/fonts/plusjakartasans_semibold.ttf
    - family: pingfang
      fonts:
        - asset: assets/fonts/PingFang_SC_Medium.otf
        - asset: assets/fonts/PingFang_SC_regular.otf
    - family: Din
      fonts:
        - asset: assets/fonts/DIN_Alternate_Bold.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
